


// import DryCleaningIcon from '@mui/icons-material/DryCleaning';
// import LocalShippingIcon from '@mui/icons-material/LocalShipping';
// import HandymanOutlinedIcon from '@mui/icons-material/HandymanOutlined';
import PetsRoundedIcon from '@mui/icons-material/PetsRounded';
import ChildFriendlyIcon from '@mui/icons-material/ChildFriendly';
import CleaningServicesOutlinedIcon from '@mui/icons-material/CleaningServicesOutlined';
import HandshakeIcon from '@mui/icons-material/Handshake';
import LocalTaxiIcon from '@mui/icons-material/LocalTaxi';
import LocalGroceryStoreIcon from '@mui/icons-material/LocalGroceryStore';
import TakeoutDiningIcon from '@mui/icons-material/TakeoutDining';
import LocalCarWashIcon from '@mui/icons-material/LocalCarWash';


export const citiesList = [

    { key: 1, value: 'אבו ג\'ווייעד (שבט)' },
    { key: 2, value: 'אבו גוש' },
    { key: 3, value: 'אבו סנאן' },
    { key: 4, value: 'אבו סריחאן (שבט)' },
    { key: 5, value: 'אבו עבדון (שבט)' },
    { key: 6, value: 'אבו עמאר (שבט)' },
    { key: 7, value: 'אבו עמרה (שבט)' },
    { key: 8, value: 'אבו קורינאת (שבט)' },
    { key: 9, value: 'אבו קרינאת (יישוב)' },
    { key: 10, value: 'אבו רובייעה (שבט)' },
    { key: 11, value: 'אבו רוקייק (שבט)' },
    { key: 12, value: 'אבו תלול' },
    { key: 13, value: 'אבטין' },
    { key: 14, value: 'אבטליון' },
    { key: 15, value: 'אביאל' },
    { key: 16, value: 'אביבים' },
    { key: 17, value: 'אביגדור' },
    { key: 18, value: 'אביגיל' },
    { key: 19, value: 'אביחיל' },
    { key: 20, value: 'אביטל' },
    { key: 21, value: 'אביעזר' },
    { key: 22, value: 'אבירים' },
    { key: 23, value: 'אבן יהודה' },
    { key: 24, value: 'אבן מנחם' },
    { key: 25, value: 'אבן ספיר' },
    { key: 26, value: 'אבן שמואל' },
    { key: 27, value: 'אבני איתן' },
    { key: 28, value: 'אבני חפץ' },
    { key: 29, value: 'אבנת' },
    { key: 30, value: 'אבשלום' },
    { key: 31, value: 'אדורה' },
    { key: 32, value: 'אדירים' },
    { key: 33, value: 'אדמית' },
    { key: 34, value: 'אדרת' },
    { key: 35, value: 'אודים' },
    { key: 36, value: 'אודם' },
    { key: 37, value: 'אוהד' },
    { key: 38, value: 'אום אל-פחם' },
    { key: 39, value: 'אום אל-קוטוף' },
    { key: 40, value: 'אום בטין' },
    { key: 41, value: 'אומן' },
    { key: 42, value: 'אומץ' },
    { key: 43, value: 'אופקים' },
    { key: 44, value: 'אור הגנוז' },
    { key: 45, value: 'אור הנר' },
    { key: 46, value: 'אור יהודה' },
    { key: 47, value: 'אור עקיבא' },
    { key: 48, value: "אור עקיבא" },
    { key: 49, value: "אורה" },
    { key: 50, value: "אורות" },
    { key: 51, value: "אורטל" },
    { key: 52, value: "אורים" },
    { key: 53, value: "אורנים" },
    { key: 54, value: "אורנית" },
    { key: 55, value: "אושה" },
    { key: 56, value: "אזור" },
    { key: 57, value: "אחווה" },
    { key: 58, value: "אחוזם" },
    { key: 59, value: "אחוזת ברק" },
    { key: 60, value: "אחיהוד" },
    { key: 61, value: "אחיטוב" },
    { key: 62, value: "אחיסמך" },
    { key: 63, value: "אחיעזר" },
    { key: 64, value: "אטרש (שבט)" },
    { key: 65, value: "איבים" },
    { key: 66, value: "אייל" },
    { key: 67, value: "איילת השחר" },
    { key: 68, value: "אילון" },
    { key: 69, value: "אילות" },
    { key: 70, value: "אילניה" },
    { key: 71, value: "אילת" },
    { key: 72, value: "אירוס" },
    { key: 73, value: "איתמר" },
    { key: 74, value: "איתן" },
    { key: 75, value: "איתנים" },
    { key: 76, value: "אכסאל" },
    { key: 77, value: "אל-עזי" },
    { key: 78, value: "אל-עריאן" },
    { key: 79, value: "אל רום" },
    { key: 80, value: "אל סייד" },
    { key: 81, value: "אלומה" },
    { key: 82, value: "אלומות" },
    { key: 83, value: "אלון הגליל" },
    { key: 84, value: "אלון מורה" },
    { key: 85, value: "אלון שבות" },
    { key: 86, value: "אלוני אבא" },
    { key: 87, value: "אלוני הבשן" },
    { key: 88, value: "אלוני יצחק" },
    { key: 89, value: "אלונים" },
    { key: 90, value: "אלי-עד" },
    { key: 91, value: "אליאב" },
    { key: 92, value: "אליכין" },
    { key: 93, value: "אלישמע" },
    { key: 94, value: "אלישיב" },
    { key: 95, value: "אליקים" },
    { key: 96, value: "אליפלט" },
    { key: 97, value: "אליפז" },
    { key: 98, value: "אלקוש" },
    { key: 99, value: "אלעד" },
    { key: 100, value: "אלעזר" },
    { key: 101, value: "אלפי מנשה" },
    { key: 102, value: "אלקנה" },
    { key: 103, value: "אלרום" },
    { key: 104, value: "אלמוג" },
    { key: 105, value: "אלמגור" },
    { key: 106, value: "אמונים" },
    { key: 107, value: "אמנון" },
    { key: 108, value: "אמציה" },
    { key: 109, value: "אניעם" },
    { key: 110, value: "אסד (שבט)" },
    { key: 111, value: "אספר" },
    { key: 112, value: "אעבלין" },
    { key: 113, value: "אעצם (שבט)" },
    { key: 114, value: "אפיניש (שבט)" },
    { key: 115, value: "אפיק" },
    { key: 116, value: "אפיקים" },
    { key: 117, value: "אפק" },
    { key: 118, value: "אפרת" },
    { key: 119, value: "ארבל" },
    { key: 120, value: "ארגמן" },
    { key: 121, value: "ארז" },
    { key: 122, value: "אריאל" },
    { key: 123, value: "ארסוף" },
    { key: 124, value: "אשבול" },
    { key: 125, value: "אשבל" },
    { key: 126, value: "אשדוד" },
    { key: 127, value: "אשדות יעקב (איחוד)" },
    { key: 128, value: "אשדות יעקב (מאוחד)" },
    { key: 129, value: "אשחר" },
    { key: 130, value: "אשכולות" },
    { key: 131, value: "אשל הנשיא" },
    { key: 132, value: "אשלים" },
    { key: 133, value: "אשקלון" },
    { key: 134, value: "אשרת" },
    { key: 135, value: "אשתאול" },
    { key: 136, value: "אתגר" },
    { key: 137, value: "באקה אל-גרביה" },
    { key: 138, value: "באר אורה" },
    { key: 139, value: "באר גנים" },
    { key: 140, value: "באר טוביה" },
    { key: 141, value: "באר יעקב" },
    { key: 142, value: "באר מילכה" },
    { key: 143, value: "באר שבע" },
    { key: 144, value: "בארות יצחק" },
    { key: 145, value: "בארותיים" },
    { key: 146, value: "בארי" },
    { key: 147, value: "בוסתן הגליל" },
    { key: 148, value: "בועיינה-נוג'ידאת" },
    { key: 149, value: "בוקעאתא" },
    { key: 150, value: "בורגתה" },
    { key: 151, value: "בחן" },
    { key: 152, value: "בטחה" },
    { key: 153, value: "ביצרון" },
    { key: 154, value: "ביר אל-מכסור" },
    { key: 155, value: "ביר הדאג'" },
    { key: 156, value: "ביריה" },
    { key: 157, value: "בית אורן" },
    { key: 158, value: "בית אל" },
    { key: 159, value: "בית אלעזרי" },
    { key: 160, value: "בית אלפא" },
    { key: 161, value: "בית אריה" },
    { key: 162, value: "בית ברל" },
    { key: 163, value: "בית ג'ן" },
    { key: 164, value: "בית גוברין" },
    { key: 165, value: "בית גמליאל" },
    { key: 166, value: "בית דגן" },
    { key: 167, value: "בית הגדי" },
    { key: 168, value: "בית הלוי" },
    { key: 169, value: "בית הלל" },
    { key: 170, value: "בית העמק" },
    { key: 171, value: "בית הערבה" },
    { key: 172, value: "בית השיטה" },
    { key: 173, value: "בית זיד" },
    { key: 174, value: "בית זית" },
    { key: 175, value: "בית זרע" },
    { key: 176, value: "בית חגלה" },
    { key: 177, value: "בית חורון" },
    { key: 178, value: "בית חירות" },
    { key: 179, value: "בית חלקיה" },
    { key: 180, value: "בית חנן" },
    { key: 181, value: "בית חנניה" },
    { key: 182, value: "בית חשמונאי" },
    { key: 183, value: "בית יהושע" },
    { key: 184, value: "בית יוסף" },
    { key: 185, value: "בית ינאי" },
    { key: 186, value: "בית יצחק-שער חפר" },
    { key: 187, value: "בית לחם הגלילית" },
    { key: 188, value: "בית מאיר" },
    { key: 189, value: "בית נחמיה" },
    { key: 190, value: "בית ניר" },
    { key: 191, value: "בית נקופה" },
    { key: 192, value: "בית עובד" },
    { key: 193, value: "בית עוזיאל" },
    { key: 194, value: "בית עזרא" },
    { key: 195, value: "בית עריף" },
    { key: 196, value: "בית צבי" },
    { key: 197, value: "בית קמה" },
    { key: 198, value: "בית קשת" },
    { key: 199, value: "בית רבן" },
    { key: 200, value: "בית רימון" },
    { key: 201, value: "בית שאן" },
    { key: 202, value: "בית שמש" },
    { key: 203, value: "בית שערים" },
    { key: 204, value: "בית שקמה" },
    { key: 205, value: "ביתן אהרן" },
    { key: 206, value: "ביתר עילית" },
    { key: 207, value: "בלפוריה" },
    { key: 208, value: "בן זכאי" },
    { key: 209, value: "בן עמי" },
    { key: 210, value: "בן שמן (כפר נוער)" },
    { key: 211, value: "בן שמן (מושב)" },
    { key: 212, value: "בני ברק" },
    { key: 213, value: "בני דקלים" },
    { key: 214, value: "בני דרום" },
    { key: 215, value: "בני דרור" },
    { key: 216, value: "בני יהודה" },
    { key: 217, value: "בני נצרים" },
    { key: 218, value: "בני עטרות" },
    { key: 219, value: "בני עי\"ש" },
    { key: 220, value: "בני ציון" },
    { key: 221, value: "בני ראם" },
    { key: 222, value: "בניה" },
    { key: 223, value: "בנימינה-גבעת עדה" },
    { key: 224, value: "בסמ\"ה" },
    { key: 225, value: "בסמת טבעון" },
    { key: 226, value: "בענה" },
    { key: 227, value: "בצרה" },
    { key: 228, value: "בצת" },
    { key: 229, value: "בקוע" },
    { key: 230, value: "בקעות" },
    { key: 231, value: "בר גיורא" },
    { key: 232, value: "בר יוחאי" },
    { key: 233, value: "ברוכין" },
    { key: 234, value: "ברור חיל" },
    { key: 235, value: "ברוש" },
    { key: 236, value: "ברכה" },
    { key: 237, value: "ברכיה" },
    { key: 238, value: "ברעם" },
    { key: 239, value: "ברק" },
    { key: 240, value: "ברקאי" },
    { key: 241, value: "ברקן" },
    { key: 242, value: "ברקת" },
    { key: 243, value: "בת הדר" },
    { key: 244, value: "בת חן" },
    { key: 245, value: "בת חפר" },
    { key: 246, value: "בת ים" },
    { key: 247, value: "בת עין" },
    { key: 248, value: "בת שלמה" },
    { key: 249, value: "ג'דיידה-מכר" },
    { key: 250, value: "ג'ולס" },
    { key: 251, value: "ג'לג'וליה" },
    { key: 252, value: "ג'נאביב (שבט)" },
    { key: 253, value: "ג'סר א-זרקא" },
    { key: 254, value: "ג'ש (גוש חלב)" },
    { key: 255, value: "ג'ת" },
    { key: 256, value: "גאולי תימן" },
    { key: 257, value: "גאולים" },
    { key: 258, value: "גאליה" },
    { key: 259, value: "גבולות" },
    { key: 260, value: "גבים" },
    { key: 261, value: "גבע" },
    { key: 262, value: "גבע בנימין" },
    { key: 263, value: "גבע כרמל" },
    { key: 264, value: "גבעולים" },
    { key: 265, value: "גבעון החדשה" },
    { key: 266, value: "גבעות בר" },
    { key: 267, value: "גבעות הרואה" },
    { key: 268, value: "גבעות עדן" },
    { key: 269, value: "גבעת אבני" },
    { key: 270, value: "גבעת אלה" },
    { key: 271, value: "גבעת ברנר" },
    { key: 272, value: "גבעת השלושה" },
    { key: 273, value: "גבעת זאב" },
    { key: 274, value: "גבעת ח\"ן" },
    { key: 275, value: "גבעת חיים (איחוד)" },
    { key: 276, value: "גבעת חיים (מאוחד)" },
    { key: 277, value: "גבעת יואב" },
    { key: 278, value: "גבעת יערים" },
    { key: 279, value: "גבעת ישעיהו" },
    { key: 280, value: "גבעת כ\"ח" },
    { key: 281, value: "גבעת ניל\"י" },
    { key: 282, value: "גבעת עוז" },
    { key: 283, value: "גבעת שמואל" },
    { key: 284, value: "גבעת שמש" },
    { key: 285, value: "גבעת שפירא" },
    { key: 286, value: "גבעתי" },
    { key: 287, value: "גבעתיים" },
    { key: 288, value: "גברעם" },
    { key: 289, value: "גבת" },
    { key: 290, value: "גדות" },
    { key: 291, value: "גדיש" },
    { key: 292, value: "גדעונה" },
    { key: 293, value: "גדרה" },
    { key: 294, value: "גונן" },
    { key: 295, value: "גורן" },
    { key: 296, value: "גורנות הגליל" },
    { key: 297, value: "גזית" },
    { key: 298, value: "גזר" },
    { key: 299, value: "גיאה" },
    { key: 300, value: "גיבתון" },
    { key: 301, value: "גיזו" },
    { key: 302, value: "גילון" },
    { key: 303, value: "גילת" },
    { key: 304, value: "גינוסר" },
    { key: 305, value: "גיניגר" },
    { key: 306, value: "גינתון" },
    { key: 307, value: "גיתה" },
    { key: 308, value: "גיתית" },
    { key: 309, value: "גלאון" },
    { key: 310, value: "גלגל" },
    { key: 311, value: "גליל ים" },
    { key: 312, value: "גלעד (אבן יצחק)" },
    { key: 313, value: "גמזו" },
    { key: 314, value: "גן הדרום" },
    { key: 315, value: "גן השומרון" },
    { key: 316, value: "גן חיים" },
    { key: 317, value: "גן יאשיה" },
    { key: 318, value: "גן יבנה" },
    { key: 319, value: "גן נר" },
    { key: 320, value: "גן שורק" },
    { key: 321, value: "גן שלמה" },
    { key: 322, value: "גן שמואל" },
    { key: 323, value: "גנות" },
    { key: 324, value: "גנות הדר" },
    { key: 325, value: "גני הדר" },
    { key: 326, value: "גני טל" },
    { key: 327, value: "גני יוחנן" },
    { key: 328, value: "גני מודיעין" },
    { key: 329, value: "גני עם" },
    { key: 330, value: "גני תקווה" },
    { key: 331, value: "געש" },
    { key: 332, value: "געתון" },
    { key: 333, value: "גפן" },
    { key: 334, value: "גרופית" },
    { key: 335, value: "גשור" },
    { key: 336, value: "גשר" },
    { key: 337, value: "גשר הזיו" },
    { key: 338, value: "גת (קיבוץ)" },
    { key: 339, value: "גת רימון" },
    { key: 340, value: "דאלית אל-כרמל" },
    { key: 341, value: "דבורה" },
    { key: 342, value: "דבוריה" },
    { key: 343, value: "דביר" },
    { key: 344, value: "דברת" },
    { key: 345, value: "דגניה א'" },
    { key: 346, value: "דגניה ב'" },
    { key: 347, value: "דוב\"ב" },
    { key: 348, value: "דולב" },
    { key: 349, value: "דור" },
    { key: 350, value: "דורות" },
    { key: 351, value: "דחי" },
    { key: 352, value: "דייר אל-אסד" },
    { key: 353, value: "דייר חנא" },
    { key: 354, value: "דייר ראפאת" },
    { key: 355, value: "דימונה" },
    { key: 356, value: "דישון" },
    { key: 357, value: "דליה" },
    { key: 358, value: "דלתון" },
    { key: 359, value: "דמיידה" },
    { key: 360, value: "דן" },
    { key: 361, value: "דפנה" },
    { key: 362, value: "דקל" },
    { key: 363, value: "דריג'את" },
    { key: 364, value: "האון" },
    { key: 365, value: "הבונים" },
    { key: 366, value: "הגושרים" },
    { key: 367, value: "הדר עם" },
    { key: 368, value: "הוד השרון" },
    { key: 369, value: "הודיה" },
    { key: 370, value: "הודיות" },
    { key: 371, value: "הוואשלה (שבט)" },
    { key: 372, value: "הוזייל (שבט)" },
    { key: 373, value: "הושעיה" },
    { key: 374, value: "הזורע" },
    { key: 375, value: "הזורעים" },
    { key: 376, value: "החותרים" },
    { key: 377, value: "היוגב" },
    { key: 378, value: "הילה" },
    { key: 379, value: "המעפיל" },
    { key: 380, value: "הסוללים" },
    { key: 381, value: "העוגן" },
    { key: 382, value: "הר אדר" },
    { key: 383, value: "הר גילה" },
    { key: 384, value: "הר עמשא" },
    { key: 385, value: "הראל" },
    { key: 386, value: "הרדוף" },
    { key: 387, value: "הרצליה" },
    { key: 388, value: "הררית" },
    { key: 389, value: "ורד יריחו" },
    { key: 390, value: "ורדון" },
    { key: 391, value: "זבארגה (שבט)" },
    { key: 392, value: "זבדיאל" },
    { key: 393, value: "זוהר" },
    { key: 394, value: "זיקים" },
    { key: 395, value: "זיתן" },
    { key: 396, value: "זכרון יעקב" },
    { key: 397, value: "זכריה" },
    { key: 398, value: "זמר" },
    { key: 399, value: "זמרת" },
    { key: 400, value: "זנוח" },
    { key: 401, value: "זרועה" },
    { key: 402, value: "זרזיר" },
    { key: 403, value: "זרחיה" },
    { key: 404, value: "ח'ואלד" },
    { key: 405, value: "ח'ואלד (שבט)" },
    { key: 406, value: "חבצלת השרון" },
    { key: 407, value: "חבר" },
    { key: 408, value: "חברון" },
    { key: 409, value: "חגור" },
    { key: 410, value: "חגי" },
    { key: 411, value: "חגלה" },
    { key: 412, value: "חד-נס" },
    { key: 413, value: "חדיד" },
    { key: 414, value: "חדרה" },
    { key: 415, value: "חוג'ייראת (ד'הרה)" },
    { key: 416, value: "חולדה" },
    { key: 417, value: "חולון" },
    { key: 418, value: "חולית" },
    { key: 419, value: "חולתה" },
    { key: 420, value: "חוסן" },
    { key: 421, value: "חוסנייה" },
    { key: 422, value: "חופית" },
    { key: 423, value: "חוקוק" },
    { key: 424, value: "חורה" },
    { key: 425, value: "חורפיש" },
    { key: 426, value: "חורשים" },
    { key: 427, value: "חזון" },
    { key: 428, value: "חיבת ציון" },
    { key: 429, value: "חיננית" },
    { key: 430, value: "חיפה" },
    { key: 431, value: "חירות" },
    { key: 432, value: "חלוץ" },
    { key: 433, value: "חלץ" },
    { key: 434, value: "חמאם" },
    { key: 435, value: "חמד" },
    { key: 436, value: "חמדיה" },
    { key: 437, value: "חמדת" },
    { key: 438, value: "חמרה" },
    { key: 439, value: "חניאל" },
    { key: 440, value: "חניתה" },
    { key: 441, value: "חנתון" },
    { key: 442, value: "חספין" },
    { key: 443, value: "חפץ חיים" },
    { key: 444, value: "חפצי-בה" },
    { key: 445, value: "חצב" },
    { key: 446, value: "חצבה" },
    { key: 447, value: "חצור-אשדוד" },
    { key: 448, value: "חצור הגלילית" },
    { key: 449, value: "חצרים" },
    { key: 450, value: "חרב לאת" },
    { key: 451, value: "חרוצים" },
    { key: 452, value: "חריש" },
    { key: 453, value: "חרמש" },
    { key: 454, value: "חרשים" },
    { key: 455, value: "חשמונאים" },
    { key: 456, value: "טבריה" },
    { key: 457, value: "טובא-זנגריה" },
    { key: 458, value: "טורעאן" },
    { key: 459, value: "טייבה" },
    { key: 460, value: "טייבה (בעמק)" },
    { key: 461, value: "טירה" },
    { key: 462, value: "טירת יהודה" },
    { key: 463, value: "טירת כרמל" },
    { key: 464, value: "טירת צבי" },
    { key: 465, value: "טל-אל" },
    { key: 466, value: "טל שחר" },
    { key: 467, value: "טללים" },
    { key: 468, value: "טלמון" },
    { key: 469, value: "טמרה" },
    { key: 470, value: "טמרה (יזרעאל)" },
    { key: 471, value: "טנא" },
    { key: 472, value: "טפחות" },
    { key: 473, value: "יאנוח-ג'ת" },
    { key: 474, value: "יבול" },
    { key: 475, value: "יבנאל" },
    { key: 476, value: "יבנה" },
    { key: 477, value: "יגור" },
    { key: 478, value: "יגל" },
    { key: 479, value: "יד בנימין" },
    { key: 480, value: "יד השמונה" },
    { key: 481, value: "יד חנה" },
    { key: 482, value: "יד מרדכי" },
    { key: 483, value: "יד נתן" },
    { key: 484, value: "יד רמב\"ם" },
    { key: 485, value: "ידידה" },
    { key: 486, value: "יהוד-מונוסון" },
    { key: 487, value: "יהל" },
    { key: 488, value: "יובל" },
    { key: 489, value: "יובלים" },
    { key: 490, value: "יודפת" },
    { key: 491, value: "יונתן" },
    { key: 492, value: "יושיביה" },
    { key: 493, value: "יזרעאל" },
    { key: 494, value: "יחיעם" },
    { key: 495, value: "יטבתה" },
    { key: 496, value: "ייט\"ב" },
    { key: 497, value: "יכיני" },
    { key: 498, value: "ינוב" },
    { key: 499, value: "ינון" },
    { key: 500, value: "יסוד המעלה" },
    { key: 501, value: "יסודות" },
    { key: 502, value: "יסעור" },
    { key: 503, value: "יעד" },
    { key: 504, value: "יעל" },
    { key: 505, value: "יעף" },
    { key: 506, value: "יערה" },
    { key: 507, value: "יפיע" },
    { key: 508, value: "יפית" },
    { key: 509, value: "יפעת" },
    { key: 510, value: "יפתח" },
    { key: 511, value: "יצהר" },
    { key: 512, value: "יציץ" },
    { key: 513, value: "יקום" },
    { key: 514, value: "יקיר" },
    { key: 515, value: "יקנעם (מושבה)" },
    { key: 516, value: "יקנעם עילית" },
    { key: 517, value: "יראון" },
    { key: 518, value: "ירדנה" },
    { key: 519, value: "ירוחם" },
    { key: 520, value: "ירושלים" },
    { key: 521, value: "ירחיב" },
    { key: 522, value: "ירכא" },
    { key: 523, value: "ירקונה" },
    { key: 524, value: "ישע" },
    { key: 525, value: "ישעי" },
    { key: 526, value: "ישרש" },
    { key: 527, value: "יתד" },
    { key: 528, value: "כאבול" },
    { key: 529, value: "כאוכב אבו אל-היג'א" },
    { key: 530, value: "כברי" },
    { key: 531, value: "כדורי" },
    { key: 532, value: "כדיתה" },
    { key: 533, value: "כוכב השחר" },
    { key: 534, value: "כוכב יאיר" },
    { key: 535, value: "כוכב יעקב" },
    { key: 536, value: "כוכב מיכאל" },
    { key: 537, value: "כורזים" },
    { key: 538, value: "כחל" },
    { key: 539, value: "כחלה" },
    { key: 540, value: "כיסופים" },
    { key: 541, value: "כישור" },
    { key: 542, value: "כליל" },
    { key: 543, value: "כלנית" },
    { key: 544, value: "כמאנה" },
    { key: 545, value: "כמהין" },
    { key: 546, value: "כמון" },
    { key: 547, value: "כנות" },
    { key: 548, value: "כנף" },
    { key: 549, value: "כנרת (מושבה)" },
    { key: 550, value: "כנרת (קבוצה)" },
    { key: 551, value: "כסיפה" },
    { key: 552, value: "כסלון" },
    { key: 553, value: "כסרא-סמיע" },
    { key: 554, value: "כעביה-טבאש-חג'אג'רה" },
    { key: 555, value: "כפר אביב" },
    { key: 556, value: "כפר אדומים" },
    { key: 557, value: "כפר אוריה" },
    { key: 558, value: "כפר אחים" },
    { key: 559, value: "כפר ביאליק" },
    { key: 560, value: "כפר ביל\"ו" },
    { key: 561, value: "כפר בלום" },
    { key: 562, value: "כפר בן נון" },
    { key: 563, value: "כפר ברא" },
    { key: 564, value: "כפר ברוך" },
    { key: 565, value: "כפר גדעון" },
    { key: 566, value: "כפר גלים" },
    { key: 567, value: "כפר גליקסון" },
    { key: 568, value: "כפר גלעדי" },
    { key: 569, value: "כפר דניאל" },
    { key: 570, value: "כפר האורנים" },
    { key: 571, value: "כפר החורש" },
    { key: 572, value: "כפר המכבי" },
    { key: 573, value: "כפר הנגיד" },
    { key: 574, value: "כפר הנוער הדתי" },
    { key: 575, value: "כפר הנשיא" },
    { key: 576, value: "כפר הס" },
    { key: 577, value: "כפר הרא\"ה" },
    { key: 578, value: "כפר הרי\"ף" },
    { key: 579, value: "כפר ויתקין" },
    { key: 580, value: "כפר ורבורג" },
    { key: 581, value: "כפר ורדים" },
    { key: 582, value: "כפר זוהרים" },
    { key: 583, value: "כפר זיתים" },
    { key: 584, value: "כפר חב\"ד" },
    { key: 585, value: "כפר חושן" },
    { key: 586, value: "כפר חיטים" },
    { key: 587, value: "כפר חיים" },
    { key: 588, value: "כפר חנניה" },
    { key: 589, value: "כפר חסידים א'" },
    { key: 590, value: "כפר חסידים ב'" },
    { key: 591, value: "כפר חרוב" },
    { key: 592, value: "כפר טרומן" },
    { key: 593, value: "כפר יאסיף" },
    { key: 594, value: "כפר ידידיה" },
    { key: 595, value: "כפר יהושע" },
    { key: 596, value: "כפר יונה" },
    { key: 597, value: "כפר יחזקאל" },
    { key: 598, value: "כפר יעבץ" },
    { key: 599, value: "כפר כמא" },
    { key: 600, value: "כפר כנא" },
    { key: 601, value: "כפר מונש" },
    { key: 602, value: "כפר מימון" },
    { key: 603, value: "כפר מל\"ל" },
    { key: 604, value: "כפר מנדא" },
    { key: 605, value: "כפר מנחם" },
    { key: 606, value: "כפר מסריק" },
    { key: 607, value: "כפר מצר" },
    { key: 608, value: "כפר מרדכי" },
    { key: 609, value: "כפר נטר" },
    { key: 610, value: "כפר סאלד" },
    { key: 611, value: "כפר סבא" },
    { key: 612, value: "כפר סילבר" },
    { key: 613, value: "כפר סירקין" },
    { key: 614, value: "כפר עבודה" },
    { key: 615, value: "כפר עזה" },
    { key: 616, value: "כפר עציון" },
    { key: 617, value: "כפר פינס" },
    { key: 618, value: "כפר קאסם" },
    { key: 619, value: "כפר קיש" },
    { key: 620, value: "כפר קרע" },
    { key: 621, value: "כפר ראש הנקרה" },
    { key: 622, value: "כפר רוזנואלד (זרעית)" },
    { key: 623, value: "כפר רופין" },
    { key: 624, value: "כפר רות" },
    { key: 625, value: "כפר שמאי" },
    { key: 626, value: "כפר שמואל" },
    { key: 627, value: "כפר שמריהו" },
    { key: 628, value: "כפר תבור" },
    { key: 629, value: "כפר תפוח" },
    { key: 630, value: "כרי דשא" },
    { key: 631, value: "כרכום" },
    { key: 632, value: "כרם ביבנה (ישיבה)" },
    { key: 633, value: "כרם בן זמרה" },
    { key: 634, value: "כרם בן שמן" },
    { key: 635, value: "כרם מהר\"ל" },
    { key: 636, value: "כרם שלום" },
    { key: 637, value: "כרמי יוסף" },
    { key: 638, value: "כרמי צור" },
    { key: 639, value: "כרמי קטיף" },
    { key: 640, value: "כרמיאל" },
    { key: 641, value: "כרמיה" },
    { key: 642, value: "כרמים" },
    { key: 643, value: "כרמל" },
    { key: 644, value: "לא רשום" },
    { key: 645, value: "לבון" },
    { key: 646, value: "לביא" },
    { key: 647, value: "לבנים" },
    { key: 648, value: "להב" },
    { key: 649, value: "להבות הבשן" },
    { key: 650, value: "להבות חביבה" },
    { key: 651, value: "להבים" },
    { key: 652, value: "לוד" },
    { key: 653, value: "לוזית" },
    { key: 654, value: "לוחמי הגיטאות" },
    { key: 655, value: "לוטם" },
    { key: 656, value: "לוטן" },
    { key: 657, value: "לימן" },
    { key: 658, value: "לכיש" },
    { key: 659, value: "לפיד" },
    { key: 660, value: "לפידות" },
    { key: 661, value: "לקיה" },
    { key: 662, value: "מאור" },
    { key: 663, value: "מאיר שפיה" },
    { key: 664, value: "מבוא ביתר" },
    { key: 665, value: "מבוא דותן" },
    { key: 666, value: "מבוא חורון" },
    { key: 667, value: "מבוא חמה" },
    { key: 668, value: "מבוא מודיעים" },
    { key: 669, value: "מבואות ים" },
    { key: 670, value: "מבואות יריחו" },
    { key: 671, value: "מבועים" },
    { key: 672, value: "מבטחים" },
    { key: 673, value: "מבקיעים" },
    { key: 674, value: "מבשרת ציון" },
    { key: 675, value: "מג'ד אל-כרום" },
    { key: 676, value: "מג'דל שמס" },
    { key: 677, value: "מגאר" },
    { key: 678, value: "מגדים" },
    { key: 679, value: "מגדל" },
    { key: 680, value: "מגדל העמק" },
    { key: 681, value: "מגדל עוז" },
    { key: 682, value: "מגדלים" },
    { key: 683, value: "מגידו" },
    { key: 684, value: "מגל" },
    { key: 685, value: "מגן" },
    { key: 686, value: "מגן שאול" },
    { key: 687, value: "מגשימים" },
    { key: 688, value: "מדרך עוז" },
    { key: 689, value: "מדרשת בן גוריון" },
    { key: 690, value: "מדרשת רופין" },
    { key: 691, value: "מודיעין-מכבים-רעות" },
    { key: 692, value: "מודיעין עילית" },
    { key: 693, value: "מולדת" },
    { key: 694, value: "מוצא עילית" },
    { key: 695, value: "מוקייבלה" },
    { key: 696, value: "מורן" },
    { key: 697, value: "מורשת" },
    { key: 698, value: "מזור" },
    { key: 699, value: "מזכרת בתיה" },
    { key: 700, value: "מזרע" },
    { key: 701, value: "מזרעה" },
    { key: 702, value: "מחולה" },
    { key: 703, value: "מחנה הילה" },
    { key: 704, value: "מחנה טלי" },
    { key: 705, value: "מחנה יהודית" },
    { key: 706, value: "מחנה יוכבד" },
    { key: 707, value: "מחנה יפה" },
    { key: 708, value: "מחנה יתיר" },
    { key: 709, value: "מחנה מרים" },
    { key: 710, value: "מחנה תל נוף" },
    { key: 711, value: "מחניים" },
    { key: 712, value: "מחסיה" },
    { key: 713, value: "מטולה" },
    { key: 714, value: "מטע" },
    { key: 715, value: "מי עמי" },
    { key: 716, value: "מיטב" },
    { key: 717, value: "מיטל" },
    { key: 718, value: "מייסר" },
    { key: 719, value: "מיצר" },
    { key: 720, value: "מירב" },
    { key: 721, value: "מירון" },
    { key: 722, value: "מישר" },
    { key: 723, value: "מיתר" },
    { key: 724, value: "מכורה" },
    { key: 725, value: "מכחול" },
    { key: 726, value: "מכמורת" },
    { key: 727, value: "מכמנים" },
    { key: 728, value: "מלאה" },
    { key: 729, value: "מלילות" },
    { key: 730, value: "מלכיה" },
    { key: 731, value: "מנוחה" },
    { key: 732, value: "מנוף" },
    { key: 733, value: "מנות" },
    { key: 734, value: "מנחמיה" },
    { key: 735, value: "מנרה" },
    { key: 736, value: "מנשית זבדה" },
    { key: 737, value: "מסד" },
    { key: 738, value: "מסדה" },
    { key: 739, value: "מסילות" },
    { key: 740, value: "מסילת ציון" },
    { key: 741, value: "מסלול" },
    { key: 742, value: "מסעדה" },
    { key: 743, value: "מסעודין אל-עזאזמה" },
    { key: 744, value: "מעברות" },
    { key: 745, value: "מעגלים" },
    { key: 746, value: "מעגן" },
    { key: 747, value: "מעגן מיכאל" },
    { key: 748, value: "מעוז חיים" },
    { key: 749, value: "מעון" },
    { key: 750, value: "מעונה" },
    { key: 751, value: "מעיליא" },
    { key: 752, value: "מעין ברוך" },
    { key: 753, value: "מעין צבי" },
    { key: 754, value: "מעלה אדומים" },
    { key: 755, value: "מעלה אפרים" },
    { key: 756, value: "מעלה גלבוע" },
    { key: 757, value: "מעלה גמלא" },
    { key: 758, value: "מעלה החמישה" },
    { key: 759, value: "מעלה לבונה" },
    { key: 760, value: "מעלה מכמש" },
    { key: 761, value: "מעלה עירון" },
    { key: 762, value: "מעלות-תרשיחא" },
    { key: 763, value: "מענית" },
    { key: 764, value: "מעש" },
    { key: 765, value: "מפלסים" },
    { key: 766, value: "מצדות יהודה" },
    { key: 767, value: "מצובה" },
    { key: 768, value: "מצליח" },
    { key: 769, value: "מצפה" },
    { key: 770, value: "מצפה אבי\"ב" },
    { key: 771, value: "מצפה אילן" },
    { key: 772, value: "מצפה יריחו" },
    { key: 773, value: "מצפה נטופה" },
    { key: 774, value: "מצפה רמון" },
    { key: 775, value: "מצפה שלם" },
    { key: 776, value: "מצר" },
    { key: 777, value: "מקווה ישראל" },
    { key: 778, value: "מרגליות" },
    { key: 779, value: "מרום גולן" },
    { key: 780, value: "מרחב עם" },
    { key: 781, value: "מרחביה (מושב)" },
    { key: 782, value: "מרחביה (קיבוץ)" },
    { key: 783, value: "מרכז שפירא" },
    { key: 784, value: "משאבי שדה" },
    { key: 785, value: "משגב דב" },
    { key: 786, value: "משגב עם" },
    { key: 787, value: "משהד" },
    { key: 788, value: "משואה" },
    { key: 789, value: "משואות יצחק" },
    { key: 790, value: "משכיות" },
    { key: 791, value: "משמר איילון" },
    { key: 792, value: "משמר דוד" },
    { key: 793, value: "משמר הירדן" },
    { key: 794, value: "משמר הנגב" },
    { key: 795, value: "משמר העמק" },
    { key: 796, value: "משמר השבעה" },
    { key: 797, value: "משמר השרון" },
    { key: 798, value: "משמר יהודה" },
    { key: 799, value: "משמרות" },
    { key: 800, value: "משמרת" },
    { key: 801, value: "משען" },
    { key: 802, value: "מתן" },
    { key: 803, value: "מתת" },
    { key: 804, value: "מתתיהו" },
    { key: 805, value: "נאות גולן" },
    { key: 806, value: "נאות הכיכר" },
    { key: 807, value: "נאות מרדכי" },
    { key: 808, value: "נאות סמדר" },
    { key: 809, value: "נאעורה" },
    { key: 810, value: "נבטים" },
    { key: 811, value: "נגבה" },
    { key: 812, value: "נגוהות" },
    { key: 813, value: "נהורה" },
    { key: 814, value: "נהלל" },
    { key: 815, value: "נהריה" },
    { key: 816, value: "נוב" },
    { key: 817, value: "נוגה" },
    { key: 818, value: "נוה צוף" },
    { key: 819, value: "נווה" },
    { key: 820, value: "נווה אבות" },
    { key: 821, value: "נווה אור" },
    { key: 822, value: "נווה אטי\"ב" },
    { key: 823, value: "נווה אילן" },
    { key: 824, value: "נווה איתן" },
    { key: 825, value: "נווה דניאל" },
    { key: 826, value: "נווה זוהר" },
    { key: 827, value: "נווה זיו" },
    { key: 828, value: "נווה חריף" },
    { key: 829, value: "נווה ים" },
    { key: 830, value: "נווה ימין" },
    { key: 831, value: "נווה ירק" },
    { key: 832, value: "נווה מבטח" },
    { key: 833, value: "נווה מיכאל" },
    { key: 834, value: "נווה שלום" },
    { key: 835, value: "נועם" },
    { key: 836, value: "נוף איילון" },
    { key: 837, value: "נוף הגליל" },
    { key: 838, value: "נופים" },
    { key: 839, value: "נופית" },
    { key: 840, value: "נופך" },
    { key: 841, value: "נוקדים" },
    { key: 842, value: "נורדיה" },
    { key: 843, value: "נורית" },
    { key: 844, value: "נחושה" },
    { key: 845, value: "נחל עוז" },
    { key: 846, value: "נחלה" },
    { key: 847, value: "נחליאל" },
    { key: 848, value: "נחלים" },
    { key: 849, value: "נחם" },
    { key: 850, value: "נחף" },
    { key: 851, value: "נחשולים" },
    { key: 852, value: "נחשון" },
    { key: 853, value: "נחשונים" },
    { key: 854, value: "נטועה" },
    { key: 855, value: "נטור" },
    { key: 856, value: "נטע" },
    { key: 857, value: "נטעים" },
    { key: 858, value: "נטף" },
    { key: 859, value: "ניין" },
    { key: 860, value: "ניל\"י" },
    { key: 861, value: "ניצן" },
    { key: 862, value: "ניצן ב'" },
    { key: 863, value: "ניצנה (קהילת חינוך)" },
    { key: 864, value: "ניצני סיני" },
    { key: 865, value: "ניצני עוז" },
    { key: 866, value: "ניצנים" },
    { key: 867, value: "ניר אליהו" },
    { key: 868, value: "ניר בנים" },
    { key: 869, value: "ניר גלים" },
    { key: 870, value: "ניר דוד (תל עמל)" },
    { key: 871, value: "ניר ח\"ן" },
    { key: 872, value: "ניר יפה" },
    { key: 873, value: "ניר יצחק" },
    { key: 874, value: "ניר ישראל" },
    { key: 875, value: "ניר משה" },
    { key: 876, value: "ניר עוז" },
    { key: 877, value: "ניר עם" },
    { key: 878, value: "ניר עציון" },
    { key: 879, value: "ניר עקיבא" },
    { key: 880, value: "ניר צבי" },
    { key: 881, value: "נירים" },
    { key: 882, value: "נירית" },
    { key: 883, value: "נמרוד" },
    { key: 884, value: "נס הרים" },
    { key: 885, value: "נס עמים" },
    { key: 886, value: "נס ציונה" },
    { key: 887, value: "נעורים" },
    { key: 888, value: "נעלה" },
    { key: 889, value: "נעמ\"ה" },
    { key: 890, value: "נען" },
    { key: 891, value: "נערן" },
    { key: 892, value: "נצאצרה (שבט)" },
    { key: 893, value: "נצר חזני" },
    { key: 894, value: "נצר סרני" },
    { key: 895, value: "נצרת" },
    { key: 896, value: "נשר" },
    { key: 897, value: "נתיב הגדוד" },
    { key: 898, value: "נתיב הל\"ה" },
    { key: 899, value: "נתיב העשרה" },
    { key: 900, value: "נתיב השיירה" },
    { key: 901, value: "נתיבות" },
    { key: 902, value: "נתניה" },
    { key: 903, value: "סאג'ור" },
    { key: 904, value: "סאסא" },
    { key: 905, value: "סביון" },
    { key: 906, value: "סגולה" },
    { key: 907, value: "סואעד (חמרייה)" },
    { key: 908, value: "סואעד (כמאנה) (שבט)" },
    { key: 909, value: "סולם" },
    { key: 910, value: "סוסיה" },
    { key: 911, value: "סופה" },
    { key: 912, value: "סח'נין" },
    { key: 913, value: "סייד (שבט)" },
    { key: 914, value: "סלמה" },
    { key: 915, value: "סלעית" },
    { key: 916, value: "סמר" },
    { key: 917, value: "סנסנה" },
    { key: 918, value: "סעד" },
    { key: 919, value: "סעוה" },
    { key: 920, value: "סער" },
    { key: 921, value: "ספיר" },
    { key: 922, value: "סתריה" },
    { key: 923, value: "ע'ג'ר" },
    { key: 924, value: "עבדון" },
    { key: 925, value: "עברון" },
    { key: 926, value: "עגור" },
    { key: 927, value: "עדי" },
    { key: 928, value: "עדנים" },
    { key: 929, value: "עוזה" },
    { key: 930, value: "עוזייר" },
    { key: 931, value: "עולש" },
    { key: 932, value: "עומר" },
    { key: 933, value: "עופר" },
    { key: 934, value: "עופרה" },
    { key: 935, value: "עוצם" },
    { key: 936, value: "עוקבי (בנו עוקבה)" },
    { key: 937, value: "עזוז" },
    { key: 938, value: "עזר" },
    { key: 939, value: "עזריאל" },
    { key: 940, value: "עזריה" },
    { key: 941, value: "עזריקם" },
    { key: 942, value: "עטאוונה (שבט)" },
    { key: 943, value: "עטרת" },
    { key: 944, value: "עידן" },
    { key: 945, value: "עיילבון" },
    { key: 946, value: "עיינות" },
    { key: 947, value: "עילוט" },
    { key: 948, value: "עין איילה" },
    { key: 949, value: "עין אל-אסד" },
    { key: 950, value: "עין גב" },
    { key: 951, value: "עין גדי" },
    { key: 952, value: "עין דור" },
    { key: 953, value: "עין הבשור" },
    { key: 954, value: "עין הוד" },
    { key: 955, value: "עין החורש" },
    { key: 956, value: "עין המפרץ" },
    { key: 957, value: "עין הנצי\"ב" },
    { key: 958, value: "עין העמק" },
    { key: 959, value: "עין השופט" },
    { key: 960, value: "עין השלושה" },
    { key: 961, value: "עין ורד" },
    { key: 962, value: "עין זיוון" },
    { key: 963, value: "עין חוד" },
    { key: 964, value: "עין חצבה" },
    { key: 965, value: "עין חרוד (איחוד)" },
    { key: 966, value: "עין חרוד (מאוחד)" },
    { key: 967, value: "עין יהב" },
    { key: 968, value: "עין יעקב" },
    { key: 969, value: "עין כרם-בי\"ס חקלאי" },
    { key: 970, value: "עין כרמל" },
    { key: 971, value: "עין מאהל" },
    { key: 972, value: "עין נקובא" },
    { key: 973, value: "עין עירון" },
    { key: 974, value: "עין צורים" },
    { key: 975, value: "עין קנייא" },
    { key: 976, value: "עין ראפה" },
    { key: 977, value: "עין שמר" },
    { key: 978, value: "עין שריד" },
    { key: 979, value: "עין תמר" },
    { key: 980, value: "עינת" },
    { key: 981, value: "עיר אובות" },
    { key: 982, value: "עכו" },
    { key: 983, value: "עלומים" },
    { key: 984, value: "עלי" },
    { key: 985, value: "עלי זהב" },
    { key: 986, value: "עלמה" },
    { key: 987, value: "עלמון" },
    { key: 988, value: "עמוקה" },
    { key: 989, value: "עמיחי" },
    { key: 990, value: "עמינדב" },
    { key: 991, value: "עמיעד" },
    { key: 992, value: "עמיעוז" },
    { key: 993, value: "עמיקם" },
    { key: 994, value: "עמיר" },
    { key: 995, value: "עמנואל" },
    { key: 996, value: "עמקה" },
    { key: 997, value: "ענב" },
    { key: 998, value: "עספיא" },
    { key: 999, value: "עפולה" },
    { key: 1000, value: "עצמון שגב" },
    { key: 1001, value: "עראבה" },
    { key: 1002, value: "עראמשה" },
    { key: 1003, value: "ערב אל נעים" },
    { key: 1004, value: "ערד" },
    { key: 1005, value: "ערוגות" },
    { key: 1006, value: "ערערה-בנגב" },
    { key: 1007, value: "ערערה" },
    { key: 1008, value: "עשהאל" },
    { key: 1009, value: "עשרת" },
    { key: 1010, value: "עתלית" },
    { key: 1011, value: "עתניאל" },
    { key: 1012, value: "פארן" },
    { key: 1013, value: "פדואל" },
    { key: 1014, value: "פדויים" },
    { key: 1015, value: "פדיה" },
    { key: 1016, value: "פוריה - כפר עבודה" },
    { key: 1017, value: "פוריה - נווה עובד" },
    { key: 1018, value: "פוריה עילית" },
    { key: 1019, value: "פוריידיס" },
    { key: 1020, value: "פורת" },
    { key: 1021, value: "פטיש" },
    { key: 1022, value: "פלך" },
    { key: 1023, value: "פלמחים" },
    { key: 1024, value: "פני חבר" },
    { key: 1025, value: "פסגות" },
    { key: 1026, value: "פסוטה" },
    { key: 1027, value: "פעמי תש\"ז" },
    { key: 1028, value: "פצאל" },
    { key: 1029, value: "פקיעין (בוקייעה)" },
    { key: 1030, value: "פקיעין חדשה" },
    { key: 1031, value: "פרדס חנה-כרכור" },
    { key: 1032, value: "פרדסיה" },
    { key: 1033, value: "פרוד" },
    { key: 1034, value: "פרזון" },
    { key: 1035, value: "פרי גן" },
    { key: 1036, value: "פתח תקווה" },
    { key: 1037, value: "פתחיה" },
    { key: 1038, value: "צאלים" },
    { key: 1039, value: "צביה" },
    { key: 1040, value: "צבעון" },
    { key: 1041, value: "צובה" },
    { key: 1042, value: "צוחר" },
    { key: 1043, value: "צופיה" },
    { key: 1044, value: "צופים" },
    { key: 1045, value: "צופית" },
    { key: 1046, value: "צופר" },
    { key: 1047, value: "צוקי ים" },
    { key: 1048, value: "צוקים" },
    { key: 1049, value: "צור הדסה" },
    { key: 1050, value: "צור יצחק" },
    { key: 1051, value: "צור משה" },
    { key: 1052, value: "צור נתן" },
    { key: 1053, value: "צוריאל" },
    { key: 1054, value: "צורית" },
    { key: 1055, value: "ציפורי" },
    { key: 1056, value: "צלפון" },
    { key: 1057, value: "צנדלה" },
    { key: 1058, value: "צפריה" },
    { key: 1059, value: "צפרירים" },
    { key: 1060, value: "צפת" },
    { key: 1061, value: "צרופה" },
    { key: 1062, value: "צרעה" },
    { key: 1063, value: "קבועה (שבט)" },
    { key: 1064, value: "קבוצת יבנה" },
    { key: 1065, value: "קדומים" },
    { key: 1066, value: "קדימה-צורן" },
    { key: 1067, value: "קדמה" },
    { key: 1068, value: "קדמת צבי" },
    { key: 1069, value: "קדר" },
    { key: 1070, value: "קדרון" },
    { key: 1071, value: "קדרים" },
    { key: 1072, value: "קודייראת א-צאנע(שבט)" },
    { key: 1073, value: "קוואעין (שבט)" },
    { key: 1074, value: "קוממיות" },
    { key: 1075, value: "קורנית" },
    { key: 1076, value: "קטורה" },
    { key: 1077, value: "קיסריה" },
    { key: 1078, value: "קלחים" },
    { key: 1079, value: "קליה" },
    { key: 1080, value: "קלנסווה" },
    { key: 1081, value: "קלע" },
    { key: 1082, value: "קציר" },
    { key: 1083, value: "קצר א-סר" },
    { key: 1084, value: "קצרין" },
    { key: 1085, value: "קרית אונו" },
    { key: 1086, value: "קרית ארבע" },
    { key: 1087, value: "קרית אתא" },
    { key: 1088, value: "קרית ביאליק" },
    { key: 1089, value: "קרית גת" },
    { key: 1090, value: "קרית טבעון" },
    { key: 1091, value: "קרית ים" },
    { key: 1092, value: "קרית יערים" },
    { key: 1093, value: "קרית יערים(מוסד)" },
    { key: 1094, value: "קרית מוצקין" },
    { key: 1095, value: "קרית מלאכי" },
    { key: 1096, value: "קרית נטפים" },
    { key: 1097, value: "קרית ענבים" },
    { key: 1098, value: "קרית עקרון" },
    { key: 1099, value: "קרית שלמה" },
    { key: 1100, value: "קרית שמונה" },
    { key: 1101, value: "קרני שומרון" },
    { key: 1102, value: "קשת" },
    { key: 1103, value: "ראמה" },
    { key: 1104, value: "ראס אל-עין" },
    { key: 1105, value: "ראס עלי" },
    { key: 1106, value: "ראש העין" },
    { key: 1107, value: "ראש פינה" },
    { key: 1108, value: "ראש צורים" },
    { key: 1109, value: "ראשון לציון" },
    { key: 1110, value: "רבבה" },
    { key: 1111, value: "רבדים" },
    { key: 1112, value: "רביבים" },
    { key: 1113, value: "רביד" },
    { key: 1114, value: "רגבה" },
    { key: 1115, value: "רגבים" },
    { key: 1116, value: "רהט" },
    { key: 1117, value: "רווחה" },
    { key: 1118, value: "רוויה" },
    { key: 1119, value: "רוח מדבר" },
    { key: 1120, value: "רוחמה" },
    { key: 1121, value: "רומאנה" },
    { key: 1122, value: "רומת הייב" },
    { key: 1123, value: "רועי" },
    { key: 1124, value: "רותם" },
    { key: 1125, value: "רחוב" },
    { key: 1126, value: "רחובות" },
    { key: 1127, value: "רחלים" },
    { key: 1128, value: "ריחאניה" },
    { key: 1129, value: "ריחן" },
    { key: 1130, value: "ריינה" },
    { key: 1131, value: "רימונים" },
    { key: 1132, value: "רינתיה" },
    { key: 1133, value: "רכסים" },
    { key: 1134, value: "רם-און" },
    { key: 1135, value: "רמות" },
    { key: 1136, value: "רמות השבים" },
    { key: 1137, value: "רמות מאיר" },
    { key: 1138, value: "רמות מנשה" },
    { key: 1139, value: "רמות נפתלי" },
    { key: 1140, value: "רמלה" },
    { key: 1141, value: "רמת גן" },
    { key: 1142, value: "רמת דוד" },
    { key: 1143, value: "רמת הכובש" },
    { key: 1144, value: "רמת השופט" },
    { key: 1145, value: "רמת השרון" },
    { key: 1146, value: "רמת טראמפ" },
    { key: 1147, value: "רמת יוחנן" },
    { key: 1148, value: "רמת ישי" },
    { key: 1149, value: "רמת מגשימים" },
    { key: 1150, value: "רמת צבי" },
    { key: 1151, value: "רמת רזיאל" },
    { key: 1152, value: "רמת רחל" },
    { key: 1153, value: "רנן" },
    { key: 1154, value: "רעים" },
    { key: 1155, value: "רעננה" },
    { key: 1156, value: "רקפת" },
    { key: 1157, value: "רשפון" },
    { key: 1158, value: "רשפים" },
    { key: 1159, value: "רתמים" },
    { key: 1160, value: "שאר ישוב" },
    { key: 1161, value: "שבי דרום" },
    { key: 1162, value: "שבי ציון" },
    { key: 1163, value: "שבי שומרון" },
    { key: 1164, value: "שבלי - אום אל-גנם" },
    { key: 1165, value: "שגב-שלום" },
    { key: 1166, value: "שדה אילן" },
    { key: 1167, value: "שדה אליהו" },
    { key: 1168, value: "שדה אליעזר" },
    { key: 1169, value: "שדה בוקר" },
    { key: 1170, value: "שדה דוד" },
    { key: 1171, value: "שדה ורבורג" },
    { key: 1172, value: "שדה יואב" },
    { key: 1173, value: "שדה יעקב" },
    { key: 1174, value: "שדה יצחק" },
    { key: 1175, value: "שדה משה" },
    { key: 1176, value: "שדה נחום" },
    { key: 1177, value: "שדה נחמיה" },
    { key: 1178, value: "שדה ניצן" },
    { key: 1179, value: "שדה עוזיהו" },
    { key: 1180, value: "שדה צבי" },
    { key: 1181, value: "שדות ים" },
    { key: 1182, value: "שדות מיכה" },
    { key: 1183, value: "שדי אברהם" },
    { key: 1184, value: "שדי חמד" },
    { key: 1185, value: "שדי תרומות" },
    { key: 1186, value: "שדמה" },
    { key: 1187, value: "שדמות דבורה" },
    { key: 1188, value: "שדמות מחולה" },
    { key: 1189, value: "שדרות" },
    { key: 1190, value: "שואבה" },
    { key: 1191, value: "שובה" },
    { key: 1192, value: "שובל" },
    { key: 1193, value: "שוהם" },
    { key: 1194, value: "שומרה" },
    { key: 1195, value: "שומריה" },
    { key: 1196, value: "שוקדה" },
    { key: 1197, value: "שורש" },
    { key: 1198, value: "שורשים" },
    { key: 1199, value: "שושנת העמקים" },
    { key: 1200, value: "שזור" },
    { key: 1201, value: "שחר" },
    { key: 1202, value: "שחרות" },
    { key: 1203, value: "שחרית" },
    { key: 1204, value: "שיבולים" },
    { key: 1205, value: "שיזף" },
    { key: 1206, value: "שיטים" },
    { key: 1207, value: "שייח' דנון" },
    { key: 1208, value: "שילה" },
    { key: 1209, value: "שילת" },
    { key: 1210, value: "שכניה" },
    { key: 1211, value: "שלווה" },
    { key: 1212, value: "שלווה במדבר" },
    { key: 1213, value: "שלוחות" },
    { key: 1214, value: "שלומי" },
    { key: 1215, value: "שלומית" },
    { key: 1216, value: "שמיר" },
    { key: 1217, value: "שמעה" },
    { key: 1218, value: "שמרת" },
    { key: 1219, value: "שמשית" },
    { key: 1220, value: "שני" },
    { key: 1221, value: "שניר" },
    { key: 1222, value: "שעב" },
    { key: 1223, value: "שעל" },
    { key: 1224, value: "שעלבים" },
    { key: 1225, value: "שער אפרים" },
    { key: 1226, value: "שער הגולן" },
    { key: 1227, value: "שער העמקים" },
    { key: 1228, value: "שער מנשה" },
    { key: 1229, value: "שער שומרון" },
    { key: 1230, value: "שפיים" },
    { key: 1231, value: "שפיר" },
    { key: 1232, value: "שפר" },
    { key: 1233, value: "שפרעם" },
    { key: 1234, value: "שקד" },
    { key: 1235, value: "שקף" },
    { key: 1236, value: "שרונה" },
    { key: 1237, value: "שריגים (לי-און)" },
    { key: 1238, value: "שריד" },
    { key: 1239, value: "שרשרת" },
    { key: 1240, value: "שתולה" },
    { key: 1241, value: "שתולים" },
    { key: 1242, value: "תאשור" },
    { key: 1243, value: "תדהר" },
    { key: 1244, value: "תובל" },
    { key: 1245, value: "תומר" },
    { key: 1246, value: "תושיה" },
    { key: 1247, value: "תימורים" },
    { key: 1248, value: "תירוש" },
    { key: 1249, value: "תל אביב - יפו" },
    { key: 1250, value: "תל יוסף" },
    { key: 1251, value: "תל יצחק" },
    { key: 1252, value: "תל מונד" },
    { key: 1253, value: "תל עדשים" },
    { key: 1254, value: "תל ציון" },
    { key: 1255, value: "תל קציר" },
    { key: 1256, value: "תל שבע" },
    { key: 1257, value: "תל תאומים" },
    { key: 1258, value: "תלם" },
    { key: 1259, value: "תלמי אליהו" },
    { key: 1260, value: "תלמי אלעזר" },
    { key: 1261, value: "תלמי ביל\"ו" },
    { key: 1262, value: "תלמי יוסף" },
    { key: 1263, value: "תלמי יחיאל" },
    { key: 1264, value: "תלמי יפה" },
    { key: 1265, value: "תלמים" },
    { key: 1266, value: "תמרת" },
    { key: 1267, value: "תנובות" },
    { key: 1268, value: "תעוז" },
    { key: 1269, value: "תפרח" },
    { key: 1270, value: "תקומה" },
    { key: 1271, value: "תקוע" },
    { key: 1272, value: "תראבין א-צאנע (שבט)" },
    { key: 1273, value: "תראבין א-צאנע (ישוב)" },
    { key: 1274, value: "תרום" }
];



export const gendersList = [
    { key: 1, value: 'זכר', finalValue: 'M' },
    { key: 2, value: 'נקבה', finalValue: 'F' },
    { key: 3, value: 'אחר', finalValue: 'O' },
];

export const categoriesList = [
    { key: 1, CatName: 'ביביסיטר', IconName: 'ChildFriendlyIcon' },
    { key: 2, CatName: 'טרמפים', IconName: 'LocalTaxiIcon' },
    { key: 3, CatName: 'ניקיון', IconName: 'CleaningServicesOutlinedIcon' },
    { key: 4, CatName: 'דוגווקינג', IconName: 'PetsRoundedIcon' },
    { key: 1003, CatName: 'שותף', IconName: 'HandshakeIcon' },
    { key: 1004, CatName: 'קניות', IconName: 'LocalGroceryStoreIcon' },
    { key: 1005, CatName: 'בישול', IconName: 'TakeoutDiningIcon' },
    { key: 1006, CatName: 'שטיפת רכב', IconName: 'LocalCarWashIcon' },
];

export const iconMapping = {
    ChildFriendlyIcon: ChildFriendlyIcon,
    LocalTaxiIcon: LocalTaxiIcon,
    CleaningServicesOutlinedIcon: CleaningServicesOutlinedIcon,
    PetsRoundedIcon: PetsRoundedIcon,
    HandshakeIcon: HandshakeIcon,
    LocalGroceryStoreIcon: LocalGroceryStoreIcon,
    TakeoutDiningIcon: TakeoutDiningIcon,
    LocalCarWashIcon: LocalCarWashIcon,
};








